I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 601, in script
    "We got the dna results and can leave the lab now."
TypeError: missing a required argument: 'location'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 601, in script
    "We got the dna results and can leave the lab now."
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 2560, in execute
    Say.execute(self)
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/exports.py", line 1494, in say
    who(what, *args, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/Applications/renpy-8.2.3-sdk/renpy/character.py", line 1045, in do_display
    display_say(who,
  File "/Applications/renpy-8.2.3-sdk/renpy/character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Applications/renpy-8.2.3-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Applications/renpy-8.2.3-sdk/renpy/display/core.py", line 2688, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Applications/renpy-8.2.3-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/core.py", line 2688, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "/Applications/renpy-8.2.3-sdk/renpy/parameter.py", line 429, in apply_arguments
    return parameters.apply(args or (), kwargs or {}, ignore_errors)
  File "/Applications/renpy-8.2.3-sdk/renpy/parameter.py", line 283, in apply
    raise TypeError(msg) # from None
TypeError: missing a required argument: 'location'

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Lab Scene 1 1.0
Thu Aug  8 12:07:07 2024
